/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.csvemail.project;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//    	SpringCSVEmailApplication classUnderTest = new SpringCSVEmailApplication();
    }
}
